[build]
  publish = "dist"
  command = "yarn build"

[context.deploy-preview]
  command = "yarn stage"

[context.branch-deploy]
  command = "yarn stage"

# These redirects are from the pre-2019 Auxano Site.
[[redirects]]
  from = "/who-we-are"
  to = "/about-us"

[[redirects]]
  from = "/people"
  to = "/team"

[[redirects]]
  from = "/investment-management"
  to = "/client-services"

[[redirects]]
  from = "/generations"
  to = "/legacy-planning"
