# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
# Limit which branches are checked
general:
  branches:
    only:
      - master
      - develop
      - /feature\/.*/
      - /fix\/.*/
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # Run test script
      - run: 
          name: ESLint Test
          command: yarn test-eslint
      
          # Test build
      - run: 
          name: Install Dependencies
          command: yarn build
      
      # Serve site
      - run:
          name: Serve Production Site
          command: yarn serve --no-clipboard
          background: true

      # Set up and run ngrok
      - run:
          name: Set up ngrok
          command: |
            wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
            unzip ngrok-stable-linux-amd64.zip -d /tmp
            chmod +x /tmp/ngrok
            /tmp/ngrok authtoken $NGROK_TOKEN
      
      - run: 
          name: Run ngrok
          command: /tmp/ngrok http 3000  --log stderr
          background: true

      # Set up JSON parser
      - run: 
          name: Set up JSON parser
          command: | 
            wget https://stedolan.github.io/jq/download/linux64/jq
            chmod +x jq

      # Wait for ngrok server to start up
      - run: sleep 3

      # Get and store PageSpeed results
      - run: 
          name: Run PageSpeed
          command: |
            mkdir tmp/results
            curl "https://www.googleapis.com/pagespeedonline/v4/runPagespeed?rule=AvoidLandingPageRedirects&rule=MainResourceServerResponseTime&rule=MinifyCss&rule=MinifyHTML&rule=MinifyJavaScript&rule=MinimizeRenderBlockingResources&rule=OptimizeImages&rule=PrioritizeVisibleContent&url=$(curl 'http://localhost:4040/api/tunnels' | ./jq -r '.tunnels[1].public_url')" > ./tmp/results/pagespeed-desktop.json
      - store_artifacts:
          path: ./tmp/results/pagespeed-desktop.json
      
      # Test Accessibility (a11y)
      - run: 
          name: Install Puppeteer Dependencies
          command: sudo apt install libx11-xcb1 # For Chromium's dependencies
      - run: 
          name: Pa11y Test
          command: yarn run --silent test-pa11y --json > ./tmp/results/pa11y-desktop.json
      - store_artifacts:
          path: ./tmp/results/pa11y-desktop.json