backend:
  name: git-gateway
  branch: master
media_folder: public/uploads
public_folder: /uploads
collections:
  - label: Pages
    name: pages
    files:
      - label: "Home Page"
        name: home
        file: src/data/pages/home.yml
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: "Subtitle"
                name: subtitle
                widget: text
              - label: "Call to Action Text"
                name: ctaText
                widget: string
              - label: "Call to Action Link"
                name: ctaLink
                widget: string
          - label: Pullquote
            name: pullquote
            widget: markdown
            buttons: ["bold", "italic", "link"]
          - label: "Learn More"
            name: learnMore
            widget: object
            fields:
              - label: "Link Text"
                name: text
                widget: string
              - label: "Link"
                name: link
                widget: string
          - label: "Subscribe"
            name: subscribe
            widget: object
            fields:
              - label: "Heading"
                name: heading
                widget: string
              - label: "Subheading"
                name: text
                widget: text
      - label: "About Us"
        name: aboutUs
        file: src/data/pages/aboutUs.yml
        fields:
          - label: "Page Title"
            name: pageTitle
            widget: string
          - label: Hero
            name: hero
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: "Subtitle"
                name: subtitle
                widget: text
              - label: "Hero Image"
                name: image
                widget: image
              - label: "Call to Action Text"
                name: ctaText
                widget: string
              - label: "Call to Action Link"
                name: ctaLink
                widget: string
          - label: "Text Pullout"
            name: textSection
            widget: markdown
            buttons: ["bold", "italic", "link"]
          - label: "Info section 1"
            name: infoSection1
            widget: object
            fields:
              - label: "Heading"
                name: heading
                widget: string
              - label: "Content"
                name: text
                widget: text
              - label: "Image"
                name: image
                widget: object
                fields:
                  - label: "Image"
                    name: src
                    widget: image
                  - label: "Image Description"
                    name: alt
                    widget: string
          - label: "Action Banner"
            name: actionBanner
            widget: object
            fields:
              - label: "Text"
                name: text
                widget: string
              - label: "Link"
                name: link
                widget: string
          - label: "Subscribe"
            name: subscribe
            widget: object
            fields:
              - label: "Heading"
                name: heading
                widget: string
              - label: "Subheading"
                name: text
                widget: text
      - label: "Our Approach"
        name: ourApproach
        file: src/data/pages/ourApproach.yml
        fields:
          - label: "Page Title"
            name: pageTitle
            widget: string
          - label: Hero
            name: hero
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
          - label: "Items"
            name: items
            widget: object
            fields:
              - label: "Item 1"
                name: item1
                widget: object
                fields:
                  - label: "Item Heading"
                    name: heading
                    widget: string
                  - label: "Item Heading"
                    name: body
                    widget: text
                  - label: "Item Image"
                    name: image
                    widget: object
                    fields:
                      - label: "Image"
                        name: src
                        widget: image
                      - label: "Image Description"
                        name: alt
                        widget: string
              - label: "Item 2"
                name: item2
                widget: object
                fields:
                  - label: "Item Heading"
                    name: heading
                    widget: string
                  - label: "Item Heading"
                    name: body
                    widget: text
                  - label: "Item Image"
                    name: image
                    widget: object
                    fields:
                      - label: "Image"
                        name: src
                        widget: image
                      - label: "Image Description"
                        name: alt
                        widget: string
              - label: "Item 3"
                name: item3
                widget: object
                fields:
                  - label: "Item Heading"
                    name: heading
                    widget: string
                  - label: "Item Heading"
                    name: body
                    widget: text
                  - label: "Item Image"
                    name: image
                    widget: object
                    fields:
                      - label: "Image"
                        name: src
                        widget: image
                      - label: "Image Description"
                        name: alt
                        widget: string
              - label: "Item 4"
                name: item4
                widget: object
                fields:
                  - label: "Item Heading"
                    name: heading
                    widget: string
                  - label: "Item Heading"
                    name: body
                    widget: text
                  - label: "Item Image"
                    name: image
                    widget: object
                    fields:
                      - label: "Image"
                        name: src
                        widget: image
                      - label: "Image Description"
                        name: alt
                        widget: string
          - label: "Action Banner"
            name: actionBanner
            widget: object
            fields:
              - label: "Text"
                name: text
                widget: string
              - label: "Link"
                name: link
                widget: string
          - label: "Subscribe"
            name: subscribe
            widget: object
            fields:
              - label: "Heading"
                name: heading
                widget: string
              - label: "Subheading"
                name: text
                widget: text
      - label: "Contact"
        name: contact
        file: src/data/pages/contact.yml
        fields:
          - label: "Page Title"
            name: pageTitle
            widget: string
          - label: "Contact Form"
            name: form
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
          - label: "Contact Information"
            name: info
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
          - label: "Image Divider"
            name: imageDivider
            widget: object
            fields:
              - label: "Image"
                name: src
                widget: image
              - label: "Image Description"
                name: alt
                widget: string
          - label: "Subscribe"
            name: subscribe
            widget: object
            fields:
              - label: "Heading"
                name: heading
                widget: string
              - label: "Subheading"
                name: text
                widget: text
      - label: "Client Services"
        name: clientServices
        file: src/data/pages/clientServices.yml
        fields:
          - label: "Client Services"
            name: pageTitle
            widget: string
          - label: "Hero"
            name: hero
            widget: object
            fields:
              - label: "Heading"
                name: title
                widget: string
          - label: "Action Banner"
            name: actionBanner
            widget: object
            fields:
              - label: "Text"
                name: text
                widget: string
              - label: "Link"
                name: link
                widget: string
          - label: "Subscribe"
            name: subscribe
            widget: object
            fields:
              - label: "Heading"
                name: heading
                widget: string
              - label: "Subheading"
                name: text
                widget: text
          - label: "Services"
            name: services
            widget: object
            fields:
              - label: "Service 1"
                name: item1
                widget: object
                fields:
                  - label: "Icon"
                    name: icon
                    widget: image
                  - label: "Heading"
                    name: heading
                    widget: string
                  - label: "Content"
                    name: text
                    widget: text
                  - label: "Link"
                    name: link
                    widget: string
              - label: "Service 2"
                name: item2
                widget: object
                fields:
                  - label: "Icon"
                    name: icon
                    widget: image
                  - label: "Heading"
                    name: heading
                    widget: string
                  - label: "Content"
                    name: text
                    widget: text
                  - label: "Link"
                    name: link
                    widget: string
              - label: "Service 3"
                name: item3
                widget: object
                fields:
                  - label: "Icon"
                    name: icon
                    widget: image
                  - label: "Heading"
                    name: heading
                    widget: string
                  - label: "Content"
                    name: text
                    widget: text
                  - label: "Link"
                    name: link
                    widget: string
              - label: "Service 4"
                name: item4
                widget: object
                fields:
                  - label: "Icon"
                    name: icon
                    widget: image
                  - label: "Heading"
                    name: heading
                    widget: string
                  - label: "Content"
                    name: text
                    widget: text
                  - label: "Link"
                    name: link
                    widget: string
              - label: "Service 5"
                name: item5
                widget: object
                fields:
                  - label: "Icon"
                    name: icon
                    widget: image
                  - label: "Heading"
                    name: heading
                    widget: string
                  - label: "Content"
                    name: text
                    widget: text
                  - label: "Link"
                    name: link
                    widget: string
              - label: "Service 6"
                name: item6
                widget: object
                fields:
                  - label: "Icon"
                    name: icon
                    widget: image
                  - label: "Heading"
                    name: heading
                    widget: string
                  - label: "Content"
                    name: text
                    widget: text
                  - label: "Link"
                    name: link
                    widget: string
          - label: "Info Section"
            name: infoSection
            widget: object
            fields:
              - label: "Icon"
                name: icon
                widget: image
              - label: "Heading"
                name: heading
                widget: string
              - label: "Content"
                name: text
                widget: text
              - label: "Image"
                name: image
                widget: object
                fields:
                  - label: "Image"
                    name: src
                    widget: image
                  - label: "Image Description"
                    name: alt
                    widget: string

      - label: "Other Page"
        name: other
        file: src/data/pages/other.yml
        fields:
          - label: "Page Title"
            name: pageTitle
            widget: string
          - label: "Title Other"
            name: title
            widget: string
          - label: "Text Other"
            name: exampleText
            widget: text
  - label: "Blog"
    name: "blog"
    folder: "src/data/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
