backend:
  name: git-gateway
  branch: master
media_folder: public/uploads
public_folder: /uploads
collections:
  -
    label: Pages
    name: pages
    files:
      -
        label: 'Home Page'
        name: home
        file: src/data/pages/home.json
        fields:
          -
            label: Hero
            name: hero
            widget: object
            fields:
              -
                label: Title
                name: title
                widget: string
              -
                label: 'Example text'
                name: exampleText
                widget: text
      -
        label: 'Other Page'
        name: other
        file: src/data/pages/other.json
        fields:
          -
            label: Other
            name: other
            widget: object
            fields:
              -
                label: 'Title Other'
                name: title
                widget: string
              -
                label: 'Text other'
                name: exampleText
                widget: text
