backend:
  name: git-gateway
  branch: master
media_folder: public/uploads
public_folder: /uploads
collections:
  -
    label: Pages
    name: pages
    files:
      -
        label: 'Home Page'
        name: home
        file: src/data/pages/home.yml
        path: /
        fields:
          -
            label: Hero
            name: hero
            widget: object
            fields:
              -
                label: Title
                name: title
                widget: string
              -
                label: 'Subtitle'
                name: subtitle
                widget: text
              -
                label: 'Call to Action Link'
                name: link
                widget: string
          -
            label: Pullquote
            name: pullquote 
            widget: object
            fields:
              -
                label: Text
                name: text
                widget: text
          -
            label: 'Three Columns'
            name: threecol
            widget: object
            fields:
              -
                label: 'Item 1'
                name: col1
                widget: object
                fields:
                  -
                    label: 'Heading'
                    name: heading
                    widget: string
                  -
                    label: 'Content'
                    name: text
                    widget: text
                  -
                    label: 'Link'
                    name: link
                    widget: string
              -
                label: 'Item 2'
                name: col2
                widget: object
                fields:
                  -
                    label: 'Heading'
                    name: heading
                    widget: string
                  -
                    label: 'Content'
                    name: text
                    widget: text
                  -
                    label: 'Link'
                    name: link
                    widget: string
              -
                label: 'Item 3'
                name: col3
                widget: object
                fields:
                  -
                    label: 'Heading'
                    name: heading
                    widget: string
                  -
                    label: 'Content'
                    name: text
                    widget: text
                  -
                    label: 'Link'
                    name: link
                    widget: string
          -
            label: 'Learn More'
            name: learnMore
            widget: object
            fields:
              -
                label: 'Link'
                name: link
                widget: string
          -
            label: 'Subscribe'
            name: subscribe
            widget: object
            fields:
              -
                label: 'Heading'
                name: heading
                widget: string
              -
                label: 'Subheading'
                name: subHeading
                widget: text
      -
        label: 'About Us'
        name: aboutUs
        file: src/data/pages/aboutUs.yml
        path: /about-us
        fields:
          -
            label: Hero
            name: hero
            widget: object
            fields:
              -
                label: Title
                name: title
                widget: string
              -
                label: 'Subtitle'
                name: subtitle
                widget: text
          -
            label: "Full width image 1"
            name: fullWidthImage1
            widget: object
            fields:
              -
                label: Image
                name: image
                widget: image
          -
            label: "Info section 1"
            name: infoSection1
            widget: object
            fields:
              -
                label: 'Heading'
                name: heading
                widget: string
              -
                label: 'Content'
                name: text
                widget: text
              -
                label: 'Link'
                name: link
                widget: string
          -
            label: 'Action Banner'
            name: actionBanner
            widget: object
            fields:
              -
                label: 'Text'
                name: text
                widget: string
              -
                label: 'Link'
                name: link
                widget: string
          -
            label: 'Subscribe'
            name: subscribe
            widget: object
            fields:
              -
                label: 'Heading'
                name: heading
                widget: string
              -
                label: 'Subheading'
                name: subHeading
                widget: text
      -
        label: 'Other Page'
        name: other
        file: src/data/pages/other.yml
        path: /other
        fields:
          -
            label: Other
            name: other
            widget: object
            fields:
              -
                label: 'Title Other'
                name: title
                widget: string
              -
                label: 'Text other'
                name: exampleText
                widget: text
  - label: "Blog"
    name: "blog"
    folder: "src/data/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
